export const products = [
    {
        _id:1,
        name:'Airpods Wirless Blutooth',
        image:'/image/airpods.jpg',
        description:'lorem2sdkfh sdhfjhdfk sdfjhsdkfjhsdf sdfjksdfkjdshfhdsuhfdsfdsjufsd',
        brand:"Apple",
        category:'Electronics',
        price:'660',
        countInStock:15,
        rating:4.5,
        numReviews:10
    },
    {
        _id:2,
        name:' Wirless Blutooth',
        image:'/image/airpods.jpg',
        description:'lorem2sdkfh sdhfjhdfk sdfjhsdkfjhsdf sdfjksdfkjdshfhdsuhfdsfdsjufsd',
        brand:"Apple",
        category:'Electronics',
        price:'660',
        countInStock:15,
        rating:4.5,
        numReviews:10
    },
    {
        _id:3,
        name:' Wirless ',
        image:'/image/airpods.jpg',
        description:'lorem2sdkfh sdhfjhdfk sdfjhsdkfjhsdf sdfjksdfkjdshfhdsuhfdsfdsjufsd',
        brand:"Apple",
        category:'Electronics',
        price:'660',
        countInStock:15,
        rating:4.5,
        numReviews:10
    },
    {
        _id:4,
        name:'Airpods Wirless Blutooth',
        image:'/image/airpods.jpg',
        description:'lorem2sdkfh sdhfjhdfk sdfjhsdkfjhsdf sdfjksdfkjdshfhdsuhfdsfdsjufsd',
        brand:"Apple",
        category:'Electronics',
        price:'660',
        countInStock:15,
        rating:4.5,
        numReviews:10
    },
    {
        _id:5,
        name:'Airpods Wirless Blutooth',
        image:'/image/airpods.jpg',
        description:'lorem2sdkfh sdhfjhdfk sdfjhsdkfjhsdf sdfjksdfkjdshfhdsuhfdsfdsjufsd',
        brand:"Apple",
        category:'Electronics',
        price:'660',
        countInStock:15,
        rating:4.5,
        numReviews:10
    },
    {
        _id:6,
        name:'Airpods Wirless Blutooth',
        image:'/image/airpods.jpg',
        description:'lorem2sdkfh sdhfjhdfk sdfjhsdkfjhsdf sdfjksdfkjdshfhdsuhfdsfdsjufsd',
        brand:"Apple",
        category:'Electronics',
        price:'660',
        countInStock:15,
        rating:4.5,
        numReviews:10
    },
    {
        _id:7,
        name:'Airpods Wirless Blutooth',
        image:'/image/airpods.jpg',
        description:'lorem2sdkfh sdhfjhdfk sdfjhsdkfjhsdf sdfjksdfkjdshfhdsuhfdsfdsjufsd',
        brand:"Apple",
        category:'Electronics',
        price:'660',
        countInStock:15,
        rating:4.5,
        numReviews:10
    },
]